services:
  webapi:
    image: webapi
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    environment:
      ConnectionStrings__rinha-db: "Host=postgres-server;Port=5432;Username=postgres;Password=9yZCv2.F}wnE~0{sxj*!Jx;Database=rinha-db"
    deploy:
      replicas: 2
    expose:
      - "5089"
    depends_on:
      postgres-server:
        condition: "service_started"
    networks:
      - rinha-network
  
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:80"
    networks:
      - rinha-network
    depends_on:
      webapi:
        condition: service_started
    restart: always
  
  postgres-server:
    image: "docker.io/pgvector/pgvector:pg17-trixie"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "9yZCv2.F}wnE~0{sxj*!Jx"
    networks:
      - rinha-network

networks:
  rinha-network:
    driver: "bridge"