// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Storage;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.Mapping;
using Pgvector;
using Pgvector.EntityFrameworkCore;
using WebApi.Entities;

#pragma warning disable 219, 612, 618
#nullable disable

namespace WebApi.Persistence.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class AntifraudResultEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "WebApi.Entities.AntifraudResult",
                typeof(AntifraudResult),
                baseEntityType,
                propertyCount: 3,
                unnamedIndexCount: 1,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(long),
                propertyInfo: typeof(AntifraudResult).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AntifraudResult).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0L);
            id.SetGetter(
                long (AntifraudResult instance) => AntifraudResultUnsafeAccessors.Id(instance),
                bool (AntifraudResult instance) => AntifraudResultUnsafeAccessors.Id(instance) == 0L);
            id.SetSetter(
                AntifraudResult (AntifraudResult instance, long value) =>
                {
                    AntifraudResultUnsafeAccessors.Id(instance) = value;
                    return instance;
                });
            id.SetMaterializationSetter(
                AntifraudResult (AntifraudResult instance, long value) =>
                {
                    AntifraudResultUnsafeAccessors.Id(instance) = value;
                    return instance;
                });
            id.SetAccessors(
                long (IInternalEntry entry) => (entry.FlaggedAsStoreGenerated(0) ? entry.ReadStoreGeneratedValue<long>(0) : (entry.FlaggedAsTemporary(0) && AntifraudResultUnsafeAccessors.Id(((AntifraudResult)(entry.Entity))) == 0L ? entry.ReadTemporaryValue<long>(0) : AntifraudResultUnsafeAccessors.Id(((AntifraudResult)(entry.Entity))))),
                long (IInternalEntry entry) => AntifraudResultUnsafeAccessors.Id(((AntifraudResult)(entry.Entity))),
                long (IInternalEntry entry) => entry.ReadOriginalValue<long>(id, 0),
                long (IInternalEntry entry) => ((InternalEntityEntry)entry).ReadRelationshipSnapshotValue<long>(id, 0));
            id.SetPropertyIndexes(
                index: 0,
                originalValueIndex: 0,
                shadowIndex: -1,
                relationshipIndex: 0,
                storeGenerationIndex: 0);
            id.TypeMapping = LongTypeMapping.Default.Clone(
                comparer: new ValueComparer<long>(
                    bool (long v1, long v2) => v1 == v2,
                    int (long v) => ((object)v).GetHashCode(),
                    long (long v) => v),
                keyComparer: new ValueComparer<long>(
                    bool (long v1, long v2) => v1 == v2,
                    int (long v) => ((object)v).GetHashCode(),
                    long (long v) => v),
                providerValueComparer: new ValueComparer<long>(
                    bool (long v1, long v2) => v1 == v2,
                    int (long v) => ((object)v).GetHashCode(),
                    long (long v) => v));
            id.SetCurrentValueComparer(new EntryCurrentValueComparer<long>(id));
            id.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            var embedding = runtimeEntityType.AddProperty(
                "Embedding",
                typeof(Vector),
                propertyInfo: typeof(AntifraudResult).GetProperty("Embedding", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AntifraudResult).GetField("<Embedding>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            embedding.SetGetter(
                Vector (AntifraudResult instance) => AntifraudResultUnsafeAccessors.Embedding(instance),
                bool (AntifraudResult instance) => AntifraudResultUnsafeAccessors.Embedding(instance) == null);
            embedding.SetSetter(
                AntifraudResult (AntifraudResult instance, Vector value) =>
                {
                    AntifraudResultUnsafeAccessors.Embedding(instance) = value;
                    return instance;
                });
            embedding.SetMaterializationSetter(
                AntifraudResult (AntifraudResult instance, Vector value) =>
                {
                    AntifraudResultUnsafeAccessors.Embedding(instance) = value;
                    return instance;
                });
            embedding.SetAccessors(
                Vector (IInternalEntry entry) => AntifraudResultUnsafeAccessors.Embedding(((AntifraudResult)(entry.Entity))),
                Vector (IInternalEntry entry) => AntifraudResultUnsafeAccessors.Embedding(((AntifraudResult)(entry.Entity))),
                Vector (IInternalEntry entry) => entry.ReadOriginalValue<Vector>(embedding, 1),
                Vector (IInternalEntry entry) => entry.GetCurrentValue<Vector>(embedding));
            embedding.SetPropertyIndexes(
                index: 1,
                originalValueIndex: 1,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            embedding.TypeMapping = VectorTypeMapping.Default.Clone(
                comparer: new ValueComparer<Vector>(
                    bool (Vector v1, Vector v2) => v1 == null && v2 == null || v1 != null && v2 != null && v1.Equals(v2),
                    int (Vector v) => ((object)v).GetHashCode(),
                    Vector (Vector v) => v),
                keyComparer: new ValueComparer<Vector>(
                    bool (Vector v1, Vector v2) => v1 == null && v2 == null || v1 != null && v2 != null && v1.Equals(v2),
                    int (Vector v) => ((object)v).GetHashCode(),
                    Vector (Vector v) => v),
                providerValueComparer: new ValueComparer<Vector>(
                    bool (Vector v1, Vector v2) => v1 == null && v2 == null || v1 != null && v2 != null && v1.Equals(v2),
                    int (Vector v) => ((object)v).GetHashCode(),
                    Vector (Vector v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "vector(14)",
                    size: 14,
                    fixedLength: true));
            embedding.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            embedding.AddAnnotation("Relational:ColumnType", "vector(14)");

            var label = runtimeEntityType.AddProperty(
                "Label",
                typeof(string),
                propertyInfo: typeof(AntifraudResult).GetProperty("Label", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AntifraudResult).GetField("<Label>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 20);
            label.SetGetter(
                string (AntifraudResult instance) => AntifraudResultUnsafeAccessors.Label(instance),
                bool (AntifraudResult instance) => AntifraudResultUnsafeAccessors.Label(instance) == null);
            label.SetSetter(
                AntifraudResult (AntifraudResult instance, string value) =>
                {
                    AntifraudResultUnsafeAccessors.Label(instance) = value;
                    return instance;
                });
            label.SetMaterializationSetter(
                AntifraudResult (AntifraudResult instance, string value) =>
                {
                    AntifraudResultUnsafeAccessors.Label(instance) = value;
                    return instance;
                });
            label.SetAccessors(
                string (IInternalEntry entry) => AntifraudResultUnsafeAccessors.Label(((AntifraudResult)(entry.Entity))),
                string (IInternalEntry entry) => AntifraudResultUnsafeAccessors.Label(((AntifraudResult)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(label, 2),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(label));
            label.SetPropertyIndexes(
                index: 2,
                originalValueIndex: 2,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            label.TypeMapping = NpgsqlStringTypeMapping.Default.Clone(
                comparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                keyComparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                providerValueComparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "character varying(20)",
                    size: 20));
            label.TypeMapping = ((NpgsqlStringTypeMapping)label.TypeMapping).Clone(npgsqlDbType: NpgsqlTypes.NpgsqlDbType.Varchar);
        label.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

        var key = runtimeEntityType.AddKey(
            new[] { id });
        runtimeEntityType.SetPrimaryKey(key);

        var index = runtimeEntityType.AddIndex(
            new[] { embedding });

        return runtimeEntityType;
    }

    public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
    {
        var id = runtimeEntityType.FindProperty("Id");
        var embedding = runtimeEntityType.FindProperty("Embedding");
        var label = runtimeEntityType.FindProperty("Label");
        var key = runtimeEntityType.FindKey(new[] { id });
        key.SetPrincipalKeyValueFactory(KeyValueFactoryFactory.CreateSimpleNonNullableFactory<long>(key));
        key.SetIdentityMapFactory(IdentityMapFactoryFactory.CreateFactory<long>(key));
        runtimeEntityType.SetOriginalValuesFactory(
            ISnapshot (IInternalEntry source) =>
            {
                var structuralType = ((AntifraudResult)(source.Entity));
                return ((ISnapshot)(new Snapshot<long, Vector, string>(((ValueComparer<long>)(((IProperty)id).GetValueComparer())).Snapshot(source.GetCurrentValue<long>(id)), (source.GetCurrentValue<Vector>(embedding) == null ? null : ((ValueComparer<Vector>)(((IProperty)embedding).GetValueComparer())).Snapshot(source.GetCurrentValue<Vector>(embedding))), (source.GetCurrentValue<string>(label) == null ? null : ((ValueComparer<string>)(((IProperty)label).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(label))))));
            });
        runtimeEntityType.SetStoreGeneratedValuesFactory(
            ISnapshot () => ((ISnapshot)(new Snapshot<long>(((ValueComparer<long>)(((IProperty)id).GetValueComparer())).Snapshot(default(long))))));
        runtimeEntityType.SetTemporaryValuesFactory(
            ISnapshot (IInternalEntry source) => ((ISnapshot)(new Snapshot<long>(default(long)))));
        runtimeEntityType.SetShadowValuesFactory(
            ISnapshot (IDictionary<string, object> source) => Snapshot.Empty);
        runtimeEntityType.SetEmptyShadowValuesFactory(
            ISnapshot () => Snapshot.Empty);
        runtimeEntityType.SetRelationshipSnapshotFactory(
            ISnapshot (IInternalEntry source) =>
            {
                var structuralType = ((AntifraudResult)(source.Entity));
                return ((ISnapshot)(new Snapshot<long>(((ValueComparer<long>)(((IProperty)id).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<long>(id)))));
            });
        runtimeEntityType.SetCounts(new PropertyCounts(
            propertyCount: 3,
            navigationCount: 0,
            complexPropertyCount: 0,
            complexCollectionCount: 0,
            originalValueCount: 3,
            shadowCount: 0,
            relationshipCount: 1,
            storeGeneratedCount: 1));
        runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
        runtimeEntityType.AddAnnotation("Relational:Schema", null);
        runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
        runtimeEntityType.AddAnnotation("Relational:TableName", "AntifraudResults");
        runtimeEntityType.AddAnnotation("Relational:ViewName", null);
        runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

        Customize(runtimeEntityType);
    }

    static partial void Customize(RuntimeEntityType runtimeEntityType);
}
}
