// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using Pgvector;
using WebApi.Entities;

#pragma warning disable 219, 612, 618
#nullable disable

namespace WebApi.Persistence.CompiledModels
{
    public static class AntifraudResultUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
        public static extern ref long Id(AntifraudResult @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Embedding>k__BackingField")]
        public static extern ref Vector Embedding(AntifraudResult @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Label>k__BackingField")]
        public static extern ref string Label(AntifraudResult @this);
    }
}
