// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using WebApi.Persistence;
using WebApi.Persistence.CompiledModels;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(AppDbContext), typeof(AppDbContextModel))]
