// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Update.Internal;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#pragma warning disable 219, 612, 618
#nullable disable

namespace WebApi.Persistence.CompiledModels
{
    public partial class AppDbContextModel
    {
        private AppDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("ac3e0e84-e963-4476-b0fb-6c1dd6a4a803"), entityTypeCount: 1)
        {
        }

        partial void Initialize()
        {
            var antifraudResult = AntifraudResultEntityType.Create(this);

            AntifraudResultEntityType.CreateAnnotations(antifraudResult);

            AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
            AddAnnotation("ProductVersion", "10.0.7");
            AddAnnotation("Relational:MaxIdentifierLength", 63);
            AddRuntimeAnnotation("Relational:RelationalModelFactory", () => CreateRelationalModel());
        }

        private IRelationalModel CreateRelationalModel()
        {
            var relationalModel = new RelationalModel(this);

            var antifraudResult = FindEntityType("WebApi.Entities.AntifraudResult")!;

            var defaultTableMappings = new List<TableMappingBase<ColumnMappingBase>>();
            antifraudResult.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings);
            var webApiEntitiesAntifraudResultTableBase = new TableBase("WebApi.Entities.AntifraudResult", null, relationalModel);
            var embeddingColumnBase = new ColumnBase<ColumnMappingBase>("Embedding", "vector(14)", webApiEntitiesAntifraudResultTableBase);
            webApiEntitiesAntifraudResultTableBase.Columns.Add("Embedding", embeddingColumnBase);
            var idColumnBase = new ColumnBase<ColumnMappingBase>("Id", "bigint", webApiEntitiesAntifraudResultTableBase);
            webApiEntitiesAntifraudResultTableBase.Columns.Add("Id", idColumnBase);
            var labelColumnBase = new ColumnBase<ColumnMappingBase>("Label", "character varying(20)", webApiEntitiesAntifraudResultTableBase);
            webApiEntitiesAntifraudResultTableBase.Columns.Add("Label", labelColumnBase);
            relationalModel.DefaultTables.Add("WebApi.Entities.AntifraudResult", webApiEntitiesAntifraudResultTableBase);
            var webApiEntitiesAntifraudResultMappingBase = new TableMappingBase<ColumnMappingBase>(antifraudResult, webApiEntitiesAntifraudResultTableBase, null);
            webApiEntitiesAntifraudResultTableBase.AddTypeMapping(webApiEntitiesAntifraudResultMappingBase, false);
            defaultTableMappings.Add(webApiEntitiesAntifraudResultMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)idColumnBase, antifraudResult.FindProperty("Id")!, webApiEntitiesAntifraudResultMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)embeddingColumnBase, antifraudResult.FindProperty("Embedding")!, webApiEntitiesAntifraudResultMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)labelColumnBase, antifraudResult.FindProperty("Label")!, webApiEntitiesAntifraudResultMappingBase);

            var tableMappings = new List<TableMapping>();
            antifraudResult.SetRuntimeAnnotation("Relational:TableMappings", tableMappings);
            var antifraudResultsTable = new Table("AntifraudResults", null, relationalModel);
            var idColumn = new Column("Id", "bigint", antifraudResultsTable);
            antifraudResultsTable.Columns.Add("Id", idColumn);
            idColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<long>(idColumn);
            idColumn.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
            var embeddingColumn = new Column("Embedding", "vector(14)", antifraudResultsTable);
            antifraudResultsTable.Columns.Add("Embedding", embeddingColumn);
            embeddingColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<Vector>(embeddingColumn);
            var labelColumn = new Column("Label", "character varying(20)", antifraudResultsTable);
            antifraudResultsTable.Columns.Add("Label", labelColumn);
            labelColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(labelColumn);
            relationalModel.Tables.Add(("AntifraudResults", null), antifraudResultsTable);
            var antifraudResultsTableMapping = new TableMapping(antifraudResult, antifraudResultsTable, null);
            antifraudResultsTable.AddTypeMapping(antifraudResultsTableMapping, false);
            tableMappings.Add(antifraudResultsTableMapping);
            RelationalModel.CreateColumnMapping(idColumn, antifraudResult.FindProperty("Id")!, antifraudResultsTableMapping);
            RelationalModel.CreateColumnMapping(embeddingColumn, antifraudResult.FindProperty("Embedding")!, antifraudResultsTableMapping);
            RelationalModel.CreateColumnMapping(labelColumn, antifraudResult.FindProperty("Label")!, antifraudResultsTableMapping);
            var pK_AntifraudResults = new UniqueConstraint("PK_AntifraudResults", antifraudResultsTable, new[] { idColumn });
            antifraudResultsTable.PrimaryKey = pK_AntifraudResults;
            pK_AntifraudResults.SetRowKeyValueFactory(new SimpleRowKeyValueFactory<long>(pK_AntifraudResults));
            var pK_AntifraudResultsKey = RelationalModel.GetKey(this,
                "WebApi.Entities.AntifraudResult",
                new[] { "Id" });
            pK_AntifraudResults.MappedKeys.Add(pK_AntifraudResultsKey);
            RelationalModel.GetOrCreateUniqueConstraints(pK_AntifraudResultsKey).Add(pK_AntifraudResults);
            antifraudResultsTable.UniqueConstraints.Add("PK_AntifraudResults", pK_AntifraudResults);
            var iX_AntifraudResults_Embedding = new TableIndex(
            "IX_AntifraudResults_Embedding", antifraudResultsTable, new[] { embeddingColumn }, false);
            iX_AntifraudResults_Embedding.SetRowIndexValueFactory(new SimpleRowIndexValueFactory<Vector>(iX_AntifraudResults_Embedding));
            var iX_AntifraudResults_EmbeddingIx = RelationalModel.GetIndex(this,
                "WebApi.Entities.AntifraudResult",
                new[] { "Embedding" });
            iX_AntifraudResults_Embedding.MappedIndexes.Add(iX_AntifraudResults_EmbeddingIx);
            RelationalModel.GetOrCreateTableIndexes(iX_AntifraudResults_EmbeddingIx).Add(iX_AntifraudResults_Embedding);
            antifraudResultsTable.Indexes.Add("IX_AntifraudResults_Embedding", iX_AntifraudResults_Embedding);
            return relationalModel.MakeReadOnly();
        }
    }
}
